### ISSUE TITLE
TxtExporter

### ISSUE THREAD

**Issue by FlorianTaube** [tillbiskup/cwepr#3] opened 2023-09-07 20:18 UTC
Hey Till,

I have unfortunately discovered another error. If you do not specify a path to a target file for the single plotter or similar, a target file is generated for the output. This is not the case with the txt exporter. If you execute it without an explicit target, the programm terminates saying "INFO - Export "v1" to file "None".

Best,
Florian

**Comment by tillbiskup** [comment] 2023-09-08 04:13
Thanks, another upstream issue that needs to be fixed in ASpecD.

Technically speaking, it is not a bug, but a missing feature, and clearly a justified one...

**Comment by tillbiskup** [comment] 2023-09-08 07:35
Currently I seem unable to reproduce the behaviour, as my tests fail when I don’t provide a file name as target. Would you mind providing an excerpt of your recipe just showing the exporter task?

**Comment by FlorianTaube** [comment] 2023-09-08 11:03
Yes, that's what I ment. Here is the recipe that I'm using in a shortened form:

- source: Filename.txt
  id: v1
  label: Experiment
  package: aspecd
  importer: TxtImporter
tasks:
- kind: processing
  type: Integration
- kind: processing
  type: BaselineCorrection
  properties:
    parameters:
      kind: polynomial
      order: 1
- kind: singleplot
  type: SinglePlotter1D
- kind: export
  type: TxtExporter

and the command line text after serving:

INFO - Import dataset "Filename.txt" as "v1"
INFO - Perform "Integration" on dataset "v1"
INFO - Perform "BaselineCorrection" on dataset "v1"
INFO - Perform "SinglePlotter1D" on dataset "v1"
INFO - Save figure from "SinglePlotter1D" to file "Filename.pdf"
INFO - Export "v1" to file "None"
ERROR - ERROR:

**Comment by tillbiskup** [comment] 2023-09-08 15:52
Thanks for the clarifications. The issue should be solved with the new release of the ASpecD framework (version 0.8.3). Please update your ASpecD package and check. If there are still problems, you may reopen the issue.

**Closed as completed by tillbiskup** 2023-09-08 15:52 UTC
